#!/usr/bin/perl -w

use strict;
use esmith::Build::CreateLinks qw(:all);


my @templates = qw(
    /etc/postfix/main.cf
    /etc/postfix/master.cf
    /etc/postfix/transport
    /etc/postfix/sasl_passwd
    /etc/postfix/tls_policy
    /etc/postfix/vmailbox
    /etc/postfix/submission_whitelist
);

#
# UPDATE event
#

event_templates('nethserver-mail-common-update', 
		@templates,
		'/etc/amavisd.conf'
    );

event_actions('nethserver-mail-common-update',
	      'initialize-default-databases' => '00',
	      'nethserver-mail-common-conf' => '20',
	      'nethserver-mail-postmap-update' => '30',
	      'firewall-adjust' => '30',
	      'runlevel-adjust' => '40');

event_services('nethserver-mail-common-update',
	       'postfix' => 'restart', 
	       'amavisd' => 'restart'
    );



#
# SAVE event
#

event_templates('nethserver-mail-common-save', @templates);

event_actions('nethserver-mail-common-save',
	      'nethserver-mail-postmap-update' => '20');

event_services('nethserver-mail-common-save',
	       'postfix' => 'reload');


#
# domain events
#

my @domainTemplates = qw(
    /etc/postfix/main.cf
    /etc/postfix/transport
    /etc/postfix/vmailbox
    /etc/postfix/virtual
    /etc/amavisd.conf
);

foreach (qw(create modify delete)) {
    event_templates('domain-' . $_, @domainTemplates);
    event_actions('domain-'   . $_, 'nethserver-mail-postmap-update' => '30');
    event_services('domain-'  . $_, 'postfix' => 'reload', 'amavisd' => 'restart');
}


#
# UNINSTALL event
#
event_actions('nethserver-mail-common-uninstall',
	      'nethserver-mail-common-uninstall' => '02',
	      'firewall-adjust' => '40',
	      'runlevel-adjust' => '50');


