#!/usr/bin/perl -w

use strict;
use esmith::Build::CreateLinks qw(:all);


my @templates = qw(
    /etc/postfix/main.cf
    /etc/postfix/master.cf
    /etc/postfix/sasl_passwd
);

#
# UPDATE event
#

event_templates('nethserver-mail-common-update', @templates);

event_actions('nethserver-mail-common-update',
	      'nethserver-mail-common-conf' => '20',
	      'firewall-adjust' => '30',
	      'runlevel-adjust' => '40');

event_services('nethserver-mail-common-update',
	       'postfix' => 'restart');



#
# SAVE event
#

event_templates('nethserver-mail-common-save', @templates);
 
event_services('nethserver-mail-common-save',
	       'postfix' => 'reload');
