#!/usr/bin/perl

#
# testsmtp.pl -- Test SMTP mail submission
#

use strict;
use Getopt::Std;
use Mail::Send;
use POSIX qw(strftime locale_h);

setlocale(LC_TIME, "en_US");

my $smtp_server = shift;
my $from_address = shift;
my $to_address = shift;
my $subject = shift;
my $timestamp = strftime("%a, %d %b %Y %H:%M:%S %z", localtime());

my $msg = Mail::Send->new;
$msg = Mail::Send->new(Subject => $subject, To => $to_address);
$msg->set('Date', $timestamp);

my $fh = $msg->open('smtp', Server => $smtp_server) || die("Could not open connection to $smtp_server\n");
print $fh <<MESSAGE;
This is the body of the message "$subject" sent on $timestamp

--
This message has been generated by testsmtp.pl script
Copyright (C) 2012 - Nethesis srl
http://www.nethesis.it
MESSAGE

$fh->close() || die("Could not send the message");
