#!/usr/bin/perl

#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;

# Refs #1478 -- prepare persistent directory for mail disclaimers:
my $disclaimerDir = '/var/lib/nethserver/mail-disclaimers';
if ( -d $disclaimerDir ) {
    my $adminGid = (getpwnam('admin'))[3];
    chmod 0775, $disclaimerDir;
    chown -1, $adminGid, $disclaimerDir;
} else {
    warn 'Directory not found! ' . $disclaimerDir;
}
