#!/usr/bin/perl

#
# nethserver-mail-postmap-update
#
# Invoke postmap on every table declared on PostmapUpdateList prop.
#
# Copyright (C) 2012 Nethesis srl
#

use strict;
use esmith::ConfigDB;

my $event = shift;


my $configDb = esmith::ConfigDB->open_ro() || die('Could not open Config DB');

my @postmapList = split(',', $configDb->get_prop('postfix', 'PostmapUpdateList'));

foreach my $db (@postmapList) {

    # prepend /etc/postfix to relative paths:
    if($db !~ qr|^/|) {
	$db = '/etc/postfix/' . $db;
    }

    if( -r $db ) {
	system('/usr/sbin/postmap', $db);
	print "postmap ". $db ."\n";
    } else {
	warn "Postfix database table $db seems to be missing..\n";
    }
}
