#!/usr/bin/perl

#
# NethServer
#
# Copyright (C) 2012 Nethesis srl
# See COPYING for licensing informations
#

use strict;
use NethServer::Service;


my @services = ('postfix', 'amavisd');

NethServer::Service::manage_add('nethserver-mail-common',
				@services);

# Refs #1478 -- prepare persistent directory for mail disclaimers:
my $disclaimerDir = '/var/lib/nethserver/mail-disclaimers';
if ( -d $disclaimerDir ) {
    my $adminGid = (getpwnam('admin'))[3];
    chmod 0775, $disclaimerDir;
    chown -1, $adminGid, $disclaimerDir;
} else {
    warn 'Directory not found! ' . $disclaimerDir;
}
