#!/usr/bin/perl

#
# NethServer
#
# Copyright (C) 2012 Nethesis srl
# See COPYING for licensing informations
#

use NethServer::Service;
use strict;

my @services = ('postfix', 'amavisd');

NethServer::Service::manage_remove('nethserver-mail-common',
				   @services);

